from __future__ import annotations

def get_templates() -> dict:
    return {
        "upper": {
            "warmup": [
                {"kind": "GENERAL", "text": "5 min easy bike/row", "duration_seconds": 300},
                {
                    "kind": "SPECIFIC",
                    "text": "10 band pull-aparts + 10 scap push-ups (optional)",
                    "duration_seconds": None,
                },
            ],
            "exercises": [
                {
                    "preferred_exercise_id": "db_bench_press",
                    "category": "COMPOUND",
                    "sets": 3,
                    "rep_min": 6,
                    "rep_max": 10,
                    "target_rpe": 7.5,
                    "rest_seconds": 120,
                    "substitutions": ["machine_chest_press", "bb_bench_press", "push_up"],
                },
                {
                    "preferred_exercise_id": "chest_supported_row",
                    "category": "COMPOUND",
                    "sets": 3,
                    "rep_min": 8,
                    "rep_max": 12,
                    "target_rpe": 7.5,
                    "rest_seconds": 90,
                    "substitutions": ["seated_cable_row", "db_one_arm_row"],
                },
                {
                    "preferred_exercise_id": "db_shoulder_press",
                    "category": "COMPOUND",
                    "sets": 2,
                    "rep_min": 8,
                    "rep_max": 12,
                    "target_rpe": 7.5,
                    "rest_seconds": 90,
                    "substitutions": ["machine_shoulder_press"],
                },
                {
                    "preferred_exercise_id": "lat_pulldown",
                    "category": "COMPOUND",
                    "sets": 2,
                    "rep_min": 8,
                    "rep_max": 12,
                    "target_rpe": 7.5,
                    "rest_seconds": 90,
                    "substitutions": ["assisted_pull_up", "cable_pullover"],
                },
                {
                    "preferred_exercise_id": "cable_curl",
                    "category": "ACCESSORY",
                    "sets": 2,
                    "rep_min": 10,
                    "rep_max": 15,
                    "target_rpe": 8.0,
                    "rest_seconds": 60,
                    "substitutions": [],
                },
                {
                    "preferred_exercise_id": "triceps_pressdown",
                    "category": "ACCESSORY",
                    "sets": 2,
                    "rep_min": 10,
                    "rep_max": 15,
                    "target_rpe": 8.0,
                    "rest_seconds": 60,
                    "substitutions": [],
                },
                {
                    "preferred_exercise_id": "dead_bug",
                    "category": "CORE",
                    "sets": 3,
                    "rep_min": 8,
                    "rep_max": 12,
                    "target_rpe": 7.0,
                    "rest_seconds": 60,
                    "substitutions": ["plank"],
                },
            ],
        },
        "lower": {
            "warmup": [
                {"kind": "GENERAL", "text": "5 min incline walk or bike", "duration_seconds": 300},
                {
                    "kind": "SPECIFIC",
                    "text": "10 bodyweight squats + 10 hip hinges",
                    "duration_seconds": None,
                },
            ],
            "exercises": [
                {
                    "preferred_exercise_id": "leg_press",
                    "category": "COMPOUND",
                    "sets": 3,
                    "rep_min": 8,
                    "rep_max": 12,
                    "target_rpe": 7.5,
                    "rest_seconds": 120,
                    "substitutions": ["goblet_squat", "hack_squat", "smith_squat"],
                },
                {
                    "preferred_exercise_id": "db_romanian_deadlift",
                    "category": "COMPOUND",
                    "sets": 3,
                    "rep_min": 6,
                    "rep_max": 10,
                    "target_rpe": 7.5,
                    "rest_seconds": 120,
                    "substitutions": ["machine_rdl", "back_extension"],
                },
                {
                    "preferred_exercise_id": "split_squat",
                    "category": "ACCESSORY",
                    "sets": 2,
                    "rep_min": 8,
                    "rep_max": 12,
                    "target_rpe": 7.5,
                    "rest_seconds": 90,
                    "substitutions": ["walking_lunge", "step_up"],
                },
                {
                    "preferred_exercise_id": "leg_curl",
                    "category": "ACCESSORY",
                    "sets": 2,
                    "rep_min": 10,
                    "rep_max": 15,
                    "target_rpe": 8.0,
                    "rest_seconds": 90,
                    "substitutions": [],
                },
                {
                    "preferred_exercise_id": "calf_raise",
                    "category": "ACCESSORY",
                    "sets": 2,
                    "rep_min": 10,
                    "rep_max": 15,
                    "target_rpe": 8.0,
                    "rest_seconds": 60,
                    "substitutions": [],
                },
                {
                    "preferred_exercise_id": "side_plank",
                    "category": "CORE",
                    "sets": 3,
                    "rep_min": 20,
                    "rep_max": 45,
                    "target_rpe": 7.0,
                    "rest_seconds": 60,
                    "substitutions": [],
                },
            ],
        },
        "full": {
            "warmup": [
                {"kind": "GENERAL", "text": "5 min row/bike", "duration_seconds": 300},
                {
                    "kind": "SPECIFIC",
                    "text": "1–2 ramp-up sets for first exercise",
                    "duration_seconds": None,
                },
            ],
            "exercises": [
                {
                    "preferred_exercise_id": "goblet_squat",
                    "category": "COMPOUND",
                    "sets": 3,
                    "rep_min": 6,
                    "rep_max": 10,
                    "target_rpe": 7.5,
                    "rest_seconds": 120,
                    "substitutions": ["leg_press", "hack_squat"],
                },
                {
                    "preferred_exercise_id": "db_bench_press",
                    "category": "COMPOUND",
                    "sets": 3,
                    "rep_min": 6,
                    "rep_max": 10,
                    "target_rpe": 7.5,
                    "rest_seconds": 120,
                    "substitutions": ["machine_chest_press"],
                },
                {
                    "preferred_exercise_id": "lat_pulldown",
                    "category": "COMPOUND",
                    "sets": 3,
                    "rep_min": 8,
                    "rep_max": 12,
                    "target_rpe": 7.5,
                    "rest_seconds": 90,
                    "substitutions": ["assisted_pull_up"],
                },
                {
                    "preferred_exercise_id": "db_romanian_deadlift",
                    "category": "COMPOUND",
                    "sets": 2,
                    "rep_min": 8,
                    "rep_max": 12,
                    "target_rpe": 7.5,
                    "rest_seconds": 120,
                    "substitutions": ["back_extension"],
                },
                {
                    "preferred_exercise_id": "farmer_carry",
                    "category": "CONDITIONING",
                    "sets": 4,
                    "rep_min": 20,
                    "rep_max": 40,
                    "target_rpe": 7.5,
                    "rest_seconds": 60,
                    "substitutions": [],
                },
                {
                    "preferred_exercise_id": "dead_bug",
                    "category": "CORE",
                    "sets": 2,
                    "rep_min": 8,
                    "rep_max": 12,
                    "target_rpe": 7.0,
                    "rest_seconds": 60,
                    "substitutions": ["plank"],
                },
            ],
        },
        "cardio": {
            "warmup": [
                {"kind": "GENERAL", "text": "5 min warmup", "duration_seconds": 300}
            ],
            "exercises": [
                {
                    "preferred_exercise_id": "cardio_zone_2",
                    "category": "CONDITIONING",
                    "sets": 1,
                    "rep_min": 1,
                    "rep_max": 1,
                    "target_rpe": 6.0,
                    "rest_seconds": 0,
                    "substitutions": [],
                }
            ],
        },
    }
